[vkbot]
token = "vkontakte_access_key"
chat_id = 123

[tgbot]
token = "telegram_bot_token"
chat_id = 456
thread_id = 123 # we have topics.

[database]
connection_uri = "postgres://user:password@host:port/dbname"
